### ISSUE TITLE
creator attributes in IOOS metadata profile v1.2

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-netcdf#30]
For the description of the `creator_url` attribute, the IOOS profile clearly states this must be the url to the _institution_.

https://github.com/ioos/ioos-metadata/blob/5b4102a5360f3171ff7bb35aff87eb5a465bf9a6/_docs/ioos-metadata-profile-v1-2.md?plain=1#L115-L116

While this is within the [ACDD 1.3 specifications](https://wiki.esipfed.org/Attribute_Convention_for_Data_Discovery_1-3#creator_url) for the `creator_url` attribute, does it need to be that narrow?

Some thoughts:
- [ ] Investigate how the attribute is being used throughout the files aligning to the IOOS Metadata Profile v1.2. Is it being used and are folks following this guidance.
- [ ] Investigate where the attribute is being read and for what purpose. How are products/end users reading that information.
- [ ] What about updating the guidance for `creator_type` to state that type should always be _institution_? This at least gets the profile in line with ACDD 1.3
- [ ] Do we need to be explicit about the `creator_url`?

**Comment by MathewBiddle** [comment]
xref: 
* https://github.com/ioos/ioos-atn-data/issues/24

**Comment by srstsavage** [comment]
We discussed this yesterday on the Sensor Map call. The motivation for limiting `creator_url` to institutions appears to be driven by the desirability of institutional websites over personal pages when displaying data in catalogs, portals, etc. On the call we agreed that relaxing the IOOS restriction on `creator_url` to match ACDD but adding some suggestions/guidance that `creator_type` always be institution made sense.

However, if certain user groups are wanting to use `creator_url` to store individual identifiers as indicated in https://github.com/ioos/ioos-atn-data/issues/24, the issue becomes more complicated. In that case, maybe the suggested guidance on `creator_type` above has to be scoped to specific data types like sensor stations, and left more open for other types.

**Comment by srstsavage** [comment]
After thinking about this for a while I think it might be best to add a new `creator_institution_url` recommended attribute to complement ACDD's `creator_institution` and relax the current IOOS `creator_url` instituion-only requirement to match ACDD. This would provide a reliable attribute to specify creator institution urls, and would also allow `creator_url` to be used for personal identifier URLs like ORCID as mentioned [here](https://github.com/ioos/ioos-atn-data/issues/24).

I created a pull request with these changes, let me know what you think.

https://github.com/ioos/ioos-metadata/pull/32

**Comment by mwengren** [comment]
In doing some IOOS Metadata Profile/ACDD research this morning/taking a walk down memory lane of our ERDDAP implementation project of years ago, I came across this diagram (~2019) which is a version of our plan at the time for mapping attributes from the IOOS Metadata Profile to the Sensor Map.  

<img width="898" height="923" alt="Image" src="https://github.com/user-attachments/assets/b1ab6c14-cbd2-4b6e-b2a0-3e93fe3c48d3" />

The goal was to have both `creator_institution` and `creator_url` consistently display the same type of info in Sensor Map, alongside the others (`publisher_` and `contributor_`).  FWIW, I'm not sure this diagram is 100% right, since it should probably show `publisher_institution` rather than `publisher_name`.

We should revisit this and verify that the changes to `creator_url` and `creator_institution_url` made in #32 have been implemented in how the present-day version of the Sensor Map station pages source their attribution.

Other background: there's an updated/final version of the Google Doc that this diagram was copied from in someone's Google Drive, but  I lost access to it.  IIRC, there were probably only minor changes made (I know we changed `info_url` to `infoUrl` in IOOS Metadata Profile 1.2 to align with ERDDAP's existing attribute naming & feedback from Bob, for example. 

Also, I couldn't remember exactly why the definition of `creator_type` was narrowed to only _institution_ originally in IMP 1.2, but I think that may have been a holdover from [IMP 1.1](https://ioos.github.io/ioos-metadata/ioos-metadata-profile-v1-1#ioos-netcdf-metadata-profile-attributes), which means it probably had something to do with mappings to [IOOS SOS Guidelines ](https://ioos.github.io/sos-guidelines/sos-wsdd-1-0.html)and [ncSOS ](https://github.com/asascience-open/ncSOS )code, which means it's probably moot at this point anyway.  

cc @srstsavage @MathewBiddle @ksauby
